version: '3.6'
services:
  customer-site-fe:
    image: rocketsgraphql/customer-site-fe:latest
    restart: always
    ports:
      - "9001:90"
    depends_on:
      - "customer-site-be"
    links:
      - "customer-site-be"
  customer-site-be:
    image: rocketsgraphql/customer-site-be:latest
    ports:
      - "5000:5000"
    restart: always
  customer-site-docs:
    # https://github.com/nuxt/nuxt.js/issues/291
    environment:
      - HOST=0.0.0.0
    image: rocketsgraphql/customer-site-docs:latest
    ports:
      - "3000:3000"
    restart: always

