version: '3.6'
services:
  customer-site-fe:
    image: rocketsgraphql/customer-site-fe:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - "customer-site-be"
    links:
      - "customer-site-be"
  customer-site-be:
    image: rocketsgraphql/customer-site-be:latest
    ports:
      - "5000:5000"
    restart: always
  customer-site-docs:
    image: rocketsgraphql/customer-site-docs:latest
    ports:
      - "3000:3000"
    restart: always

